version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  hello-world-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Hello, Worlds!"

workflows:
  hello-world-workflow:
    jobs:
      - cypress/run:
          name: run-e2e-tests
          cypress-command: npx cypress run --browser electron --headless
          start-command: npm run start:dev
      - hello-world-job
